### PR TITLE
Switch to JDK8 and upgrade cassandra-thrift to the latest available 3.7

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
@edwardcapriolo can you upgrade the CI build configuration to use JDK8? Thanks

**Comment by oscerd** [comment]
@edwardcapriolo Since I've seen you're pushing new features, can you take a look here? Thanks!

**Comment by edwardcapriolo** [comment]
thanks. Sorry that this one slipped through the cracks!

**Comment by oscerd** [comment]
Thanks @edwardcapriolo , I guess we need to switch the Travis-CI job to JDK 8

**Comment by oscerd** [comment]
@edwardcapriolo can you switch the Travis-CI job to JDK8?

**Comment by edwardcapriolo** [comment]
I switched this. The build went clean.

**Comment by edwardcapriolo** [comment]
This change was here https://github.com/edwardcapriolo/farsandra/commit/43b78e78cbd0922958a7555be2ba2d3e7fd89963 

you did not actually need me to do it :) But sorry it took so long.

**Comment by oscerd** [comment]
@edwardcapriolo yeah, you're right. I could do it by myself. Sorry for this.

**Pull request merged**
