### PR TITLE
Multi-module layout

### PR DESCRIPTION
**Pull request by agazzarini**
Hi @edwardcapriolo this contains a multi-module maven layout, according with what I described in issue #13. A couple of things:

* I renamed my packages in the maven-plugin module in order to be coherent with the farsandra naming, so classes are within io.teknek.farsandra.maven.plugin

* I moved a couple of things from between farsandra (now top level) pom.xml and farsandra-core. Dependencies are now in farsandra-core but I'm not sure about existing profiles: where is the right place to put them?

* Although, as you can see, the Maven Mojos are two simple classes (Start and Stop) I'd like to put some unit test but I'm still fighting with some Maven dependencies. 

I tested the plugin with a project of mine [1] and it works, Farsandra is started in the pre-integration-test and stopped in the post-integration-test

Let me know
Andrea

-------------------------
https://github.com/agazzarini/cumulusrdf/blob/master/cumulusrdf-integration-tests/pom.xml

### CODE REVIEW

**Comment by edwardcapriolo** [comment]
Can you provide instructions in the readme.md as to how to use this? Thanks

**Comment by edwardcapriolo** [comment]
INFO] Reactor Summary:
[INFO] 
[INFO] farsandra ......................................... SUCCESS [1.002s]
[INFO] farsandra-core .................................... SUCCESS [46.127s]
[INFO] farsandra-maven-plugin ............................ FAILURE [1.187s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.511s
[INFO] Finished at: Sun Sep 20 10:37:45 EDT 2015
[INFO] Final Memory: 24M/346M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:2.9:descriptor (default-descriptor) on project farsandra-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: io.teknek:farsandra-maven-plugin.' -> [Help 1]

**Comment by agazzarini** [comment]
2015-09-20 16:38 GMT+02:00 edwardcapriolo <notifications@github.com>:

**Comment by agazzarini** [comment]
oops, sorry, my fault, I forgot a plugin definition in pom.xml. Give me a
moment, I have to synch my project and resubmit another pull request.

After that, yes, I'll update the README

2015-09-20 17:57 GMT+02:00 Andrea Gazzarini <a.gazzarini@gmail.com>:

**Comment by agazzarini** [comment]
I submitted another pull. Now the build is ok and the README has been
updated.

Andrea

2015-09-20 18:03 GMT+02:00 Andrea Gazzarini <a.gazzarini@gmail.com>:

**Pull request merged**
