### PR TITLE
Farsandra Maven Plugin: correct pom.xml and README updated with usage & config.

### PR DESCRIPTION
**Pull request by agazzarini**
Hi @edwardcapriolo, here is the patch with the missing things. Sorry again (that was my first pull request)

### CODE REVIEW

**Comment by agazzarini** [comment]
@edwardcapriolo I noticed another annoying thing: within the farsandra-core module, some test is creating the directory "1" and "3_1" which are not ignored by git. How to ignore them? Are they fixed names so we can include them in the .gitignore? O, can we generate them under the target folder? Let me know if you want to work directly within your repository or you want me to provide a patch for this, too.

**Comment by edwardcapriolo** [comment]
That is a test. Basically we have clean-directory-on-start directive but no directive to clean on delete. Would be a good feature. I like to keep the files around to figure out what happened sometimes.

**Comment by agazzarini** [comment]
Ok, but wouldn't be enough to have those files generated within the target
directory? In that case you will have them (at least until the next "clean"
build) and they will be ignored by git (as they are in the target folder
which is already  ignored)

**Comment by edwardcapriolo** [comment]
Yes. It is a good idea to put them in the target directory.

**Pull request merged**
